package com.junbaor.huxblog.model;

public class ArticleTag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huxblog_article_tag.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huxblog_article_tag.article_bm
     *
     * @mbggenerated
     */
    private String articleBm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huxblog_article_tag.tag_bm
     *
     * @mbggenerated
     */
    private String tagBm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huxblog_article_tag.id
     *
     * @return the value of huxblog_article_tag.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huxblog_article_tag.id
     *
     * @param id the value for huxblog_article_tag.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huxblog_article_tag.article_bm
     *
     * @return the value of huxblog_article_tag.article_bm
     *
     * @mbggenerated
     */
    public String getArticleBm() {
        return articleBm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huxblog_article_tag.article_bm
     *
     * @param articleBm the value for huxblog_article_tag.article_bm
     *
     * @mbggenerated
     */
    public void setArticleBm(String articleBm) {
        this.articleBm = articleBm == null ? null : articleBm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huxblog_article_tag.tag_bm
     *
     * @return the value of huxblog_article_tag.tag_bm
     *
     * @mbggenerated
     */
    public String getTagBm() {
        return tagBm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huxblog_article_tag.tag_bm
     *
     * @param tagBm the value for huxblog_article_tag.tag_bm
     *
     * @mbggenerated
     */
    public void setTagBm(String tagBm) {
        this.tagBm = tagBm == null ? null : tagBm.trim();
    }
}