package com.junbaor.huxblog.model;

public class Tag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huxblog_tag.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huxblog_tag.bm
     *
     * @mbggenerated
     */
    private String bm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huxblog_tag.tag_name
     *
     * @mbggenerated
     */
    private String tagName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huxblog_tag.id
     *
     * @return the value of huxblog_tag.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huxblog_tag.id
     *
     * @param id the value for huxblog_tag.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huxblog_tag.bm
     *
     * @return the value of huxblog_tag.bm
     *
     * @mbggenerated
     */
    public String getBm() {
        return bm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huxblog_tag.bm
     *
     * @param bm the value for huxblog_tag.bm
     *
     * @mbggenerated
     */
    public void setBm(String bm) {
        this.bm = bm == null ? null : bm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huxblog_tag.tag_name
     *
     * @return the value of huxblog_tag.tag_name
     *
     * @mbggenerated
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huxblog_tag.tag_name
     *
     * @param tagName the value for huxblog_tag.tag_name
     *
     * @mbggenerated
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }
}